wp:
    service:
        image: komljen/wordpress
        name: wp
        port: "80"
    images:
        - ubuntu
        - mysql
        - apache
        - php-apache
        - wordpress
    links:
        - image: komljen/mysql
          name: mysql-wp
          alias: mysql

jenkins:
    service:
        image: komljen/jenkins
        name: jenkins
        port: "8080"
    images:
        - ubuntu
        - jdk-oracle
        - jenkins

redis:
    service:
        image: komljen/redis
        name: redis
        port: "6379"
    images:
        - ubuntu
        - redis

mongodb:
    service:
        image: komljen/mongodb
        name: mongodb
        port: "27017"
    images:
        - ubuntu
        - mongodb

rails-sample-app:
    service:
        image: komljen/rails-sample-app
        name: rails-sample-app
        port: "3000"
    images:
        - ubuntu
        - ruby
        - ruby-rails
        - rails-sample-app

ssg:
    service:
        image: komljen/ssg
        name: ssg
        port: "3000"
    images:
        - ubuntu
        - postgres
        - ruby
        - ruby-rails
        - ssg
    links:
        - image: komljen/postgres
          name: postgres-ssg
          alias: postgres

ghost:
    service:
        image: komljen/ghost
        name: ghost
        port: "2368"
    images:
        - ubuntu
        - nodejs
        - ghost

hipache:
    service:
        image: komljen/hipache
        name: hipache
        port: "80"
    images:
        - ubuntu
        - redis
        - nodejs
        - hipache
    links:
        - image: komljen/redis
          name: redis-hipache
          alias: redis

abh-jmeter:
    images:
        - ubuntu
        - jdk-oracle
        - maven
        - jmeter-abh

