# Generated by Django 4.1.4 on 2022-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('modified_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
    ]
